#!/bin/bash

## Files and cmd
CFG="$HOME/.config/eww/dashboard"

if [[ "$1" == "--0" ]]; then
    eww --config "$CFG" open-many --toggle system0 music0 powerbuttons0
elif [[ "$1" == "--1" ]]; then
    eww --config "$CFG" open-many --toggle system1 music1 powerbuttons1
fi

