#!/bin/bash

## Files and cmd
CFG="$HOME/.config/eww/dashboard"
if [[ "$1" == "--0" ]]; then
    eww open-many --config "$CFG" --toggle system0 music0 powerbuttons0
elif [[ "$1" == "--1" ]]; then
    eww open-many --config "$CFG" --toggle system1 music1 powerbuttons1
fi

