#!/bin/bash

while true; do
    status=$(nmcli g | tail -n 1 | awk '{print $1}')
    signal=$(nmcli -f in-use,signal dev wifi | rg "\*" | awk '{ print $2 }')
    essid=$(nmcli -t -f NAME connection show --active | head -n1 | sed 's/\"/\\"/g')

    icons=("󰤯" "󰤟" "󰤢" "󰤥" "󰤨")

    if [ "$status" = "disconnected" ] ; then
        icon="󰤮"
        color="#d3869b"
    else
        level=$(awk -v n="$signal" 'BEGIN{print int((n-1)/20)}')
        if [ "$level" -gt 4 ]; then
            level=4
        fi

    # icon=${icons[$level]}
    icon=${icons[$level]}
    color="#d3869b"
    fi

    echo '{ "essid": "'"$essid"'", "icon": "'"$icon"'", "color": "'"$color"'" }'

    sleep 3
done
