[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[font]
builtin_box_drawing = true
size = 12

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

[terminal.shell]
# program = "/usr/bin/fish"
program = "/usr/local/bin/fish"

[window]
class = "alacritty"
dynamic_title = true
opacity = 0.95

# Default colors
[colors.primary]
background = '#2D2A2E'
foreground = '#fff1f3'

# Normal colors
[colors.normal]
black   = '#2c2525'
red     = '#fd6883'
green   = '#adda78'
yellow  = '#f9cc6c'
blue    = '#f38d70'
magenta = '#a8a9eb'
cyan    = '#85dacc'
white   = '#fff1f3'

# Bright colors
[colors.bright]
black   = '#72696a'
red     = '#fd6883'
green   = '#adda78'
yellow  = '#f9cc6c'
blue    = '#f38d70'
magenta = '#a8a9eb'
cyan    = '#85dacc'
white   = '#fff1f3'

