vim.cmd("colorscheme gruvbox")
vim.cmd("hi Normal guibg=None ctermbg=None")


-- notify theme
vim.cmd("highlight NotifyERRORBorder guifg=#fb4934")
vim.cmd("highlight NotifyWARNBorder guifg=#d65d0e")
vim.cmd("highlight NotifyINFOBorder guifg=#98971a")
vim.cmd("highlight NotifyDEBUGBorder guifg=#a89984")
vim.cmd("highlight NotifyTRACEBorder guifg=#b16286")
vim.cmd("highlight NotifyERRORIcon guifg=#fb4934")
vim.cmd("highlight NotifyWARNIcon guifg=#fe8019")
vim.cmd("highlight NotifyINFOIcon guifg=#98971a")
vim.cmd("highlight NotifyDEBUGIcon guifg=#a89984")
vim.cmd("highlight NotifyTRACEIcon guifg=#b16286")
vim.cmd("highlight NotifyERRORTitle  guifg=#fb4934")
vim.cmd("highlight NotifyWARNTitle guifg=#fe8019")
vim.cmd("highlight NotifyINFOTitle guifg=#98971a")
vim.cmd("highlight NotifyDEBUGTitle  guifg=#a89984")
vim.cmd("highlight NotifyTRACETitle  guifg=#b16286")
vim.cmd("highlight link NotifyERRORBody Normal")
vim.cmd("highlight link NotifyWARNBody Normal")
vim.cmd("highlight link NotifyINFOBody Normal")
vim.cmd("highlight link NotifyDEBUGBody Normal")
vim.cmd("highlight link NotifyTRACEBody Normal")
