#!/bin/bash -x
edit_action () {
    wl-paste | swappy -f -
}
COPY=(wl-copy -t image/png)
if [ $1 = "rectangle" ]
then
    grim -g "$(slurp)" - | "${COPY}"
elif [ $1 = "screen" ]
then
    grim - | "${COPY}"
fi




ACTION=$(dunstify --action="default,Edit"  "Screenshot copied to clipboard!")

case "$ACTION" in
"default")
    edit_action
    ;;
esac
